Adjust documentation to configure live-generation of URL
sulu/SuluArticleBundle pull request #581
Opened 2021-06-15 11:36 UTC by nnatter

#### What's in this PR?

This PR adjust the documentation in the repository to allow for liver-generation of the URL inside of the article template.

#### Why?

Because the current behaviour provides a bad UX and is inconsistent to page. See #514 and #580

2021-06-15 11:39 UTC, nnatter commented on Resources/doc/article-types.md
> -The bundle provides also a way to define a `route_schema` foreach article-type.
this will only work if the template does not contain any `sulu.rlp.part` tag. as an alternative to this, the template can define a specific schema likes this (https://github.com/sulu/sulu/pull/5965):

```
<property name="routePath" type="route" mandatory="true">
    <meta>
        <title>sulu_admin.url</title>
    </meta>

    <params>
        <param name="route_schema" value="/template-prefix/{implode('-', object)}"/>
    </params>
</property>
```

2021-06-15 11:40 UTC, nnatter commented on Resources/doc/installation.md
> -        Sulu\Bundle\ArticleBundle\Document\ArticlePageDocument:
The current version of the bundle does not support article pages. I think its a bit confusing to still include them in the documentation.

2022-07-18 06:55 UTC, wachterjohannes requested changes
ELSE ACK

2022-07-18 06:55 UTC, wachterjohannes commented on Resources/doc/article-types.md
> -The bundle provides also a way to define a `route_schema` foreach article-type.
@niklasnatter then we should add that to the docs

2022-07-18 07:39 UTC, niklasnatter commented on Resources/doc/article-types.md
> -The bundle provides also a way to define a `route_schema` foreach article-type.
you are right - done 🙂

2022-07-18 07:54 UTC, wachterjohannes approved these changes

2022-07-18 07:54 UTC, merged

2022-12-28 15:44 UTC, rogamoore commented
Hi @niklasnatter,
while working on https://github.com/sulu/SuluArticleBundle/issues/538 I was wondering if when using the possibility to configure the `route_schema` directly in the XML template as described in this PR (see https://github.com/sulu/SuluArticleBundle/blob/2.x/Resources/doc/routing.md#overwrite-route-schema-in-template) if the `yaml` configuration (see https://github.com/sulu/SuluArticleBundle/blob/2.x/Resources/doc/routing.md#route-schema) is still needed?

2022-12-28 16:02 UTC, niklasnatter commented
I think the `route_schema` of the template will only be used for live generation when creating an article via the admin UI. If you create an article programatically (eg. via fixtures), only the configuration in the `.yaml` file will be used.

2022-12-28 16:46 UTC, rogamoore commented
Thanks! So the right way to achieve correct route generation programatically would be to duplicate the configuration also in the YAML file?
Is there any way to reuse the XML config?