Add List filter configuration
sulu/SuluArticleBundle pull request #632
Opened 2022-10-25 09:30 UTC by wachterjohannes

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | none
| License | MIT

#### What's in this PR?

This PR add the filter configuration for article-lists.

2022-10-25 12:32 UTC, alexander-schranz requested changes

2022-10-25 12:32 UTC, alexander-schranz commented on Metadata/ListMetadataVisitor.php
> +class ListMetadataVisitor implements ListMetadataVisitorInterface
mark services `@internal`

```suggestion
/**
 * @final
 * @internal
 */
class ListMetadataVisitor implements ListMetadataVisitorInterface
```

2022-10-27 06:46 UTC, wachterjohannes commented
@alexander-schranz fixed

2022-10-27 12:06 UTC, alexander-schranz commented on Controller/ArticleController.php
> +        $filter = $request->get('filter');
```suggestion
        $filter = $request->query->get('filter');
```

2022-10-27 12:07 UTC, wachterjohannes commented on Controller/ArticleController.php
> +        $filter = $request->get('filter');
`$request->query->get('filter')` cannot return an array 🙈

2022-10-27 12:09 UTC, alexander-schranz commented on Controller/ArticleController.php
> +        $filter = $request->get('filter');
```php
$request->query->all('filter')
```

2022-10-27 12:12 UTC, alexander-schranz commented on Controller/ArticleController.php
> +        $filter = $request->get('filter');
looks like does not exist on 4.4 so:

```php
$request->query->all()['filter'] ?? []
```

that is similar to the request get

2022-10-27 12:24 UTC, wachterjohannes commented
@alexander-schranz fixed

2022-10-27 12:56 UTC, alexander-schranz commented
Should we target this as a new feature (2.5 not released yet) or as a bugfix (2.4)? /cc @chirimoya

2022-10-27 14:48 UTC, wachterjohannes commented
@alexander-schranz is a bugfix for me 😂

2022-10-28 08:38 UTC, chirimoya commented
@wachterjohannes @alexander-schranz  `2.4`

2022-10-28 08:45 UTC, alexander-schranz approved these changes

2022-10-28 08:45 UTC, merged